import { query } from '../config/db.js';
export async function dashboard(req,res){ const [students,inside,outside,pending,active,expired,entries,exits]=await Promise.all([
  query('SELECT count(*)::int count FROM students'),query("SELECT count(*)::int count FROM students WHERE campus_status='INSIDE'"),query("SELECT count(*)::int count FROM students WHERE campus_status='OUTSIDE'"),query("SELECT count(*)::int count FROM permissions WHERE status='PENDING'"),query("SELECT count(*)::int count FROM permissions WHERE status IN ('APPROVED','ACTIVE')"),query("SELECT count(*)::int count FROM permissions WHERE status='EXPIRED'"),query("SELECT count(*)::int count FROM access_records WHERE action='ENTRY' AND timestamp::date=current_date"),query("SELECT count(*)::int count FROM access_records WHERE action='EXIT' AND timestamp::date=current_date")
 ]); res.json({students:students.rows[0].count,inside:inside.rows[0].count,outside:outside.rows[0].count,pending:pending.rows[0].count,active:active.rows[0].count,expired:expired.rows[0].count,todayEntries:entries.rows[0].count,todayExits:exits.rows[0].count}); }
export async function monitoring(req,res){ const r=await query(`SELECT s.id,s.student_id,s.full_name,s.category,s.campus_status,p.approved_return,p.status permission_status,EXTRACT(EPOCH FROM (p.approved_return-now()))/3600 remaining_hours FROM students s LEFT JOIN LATERAL (SELECT * FROM permissions WHERE student_id=s.id AND status IN ('APPROVED','ACTIVE','EXPIRED') ORDER BY created_at DESC LIMIT 1) p ON true ORDER BY s.campus_status,s.full_name`); res.json(r.rows); }
export async function alerts(req,res){ const r=await query(`SELECT a.*,s.student_id,s.full_name FROM alerts a JOIN students s ON s.id=a.student_id WHERE a.status='OPEN' ORDER BY a.created_at DESC`); res.json(r.rows); }
export async function resolveAlert(req,res){ const r=await query(`UPDATE alerts SET status='RESOLVED',resolved_at=now() WHERE id=$1 RETURNING *`,[req.params.id]); if(!r.rows[0]) return res.status(404).json({message:'Alert not found'}); res.json(r.rows[0]); }
export async function accessRecords(req,res){ const r=await query(`SELECT a.*,s.student_id,s.full_name,s.category,u.email staff_email FROM access_records a JOIN students s ON s.id=a.student_id LEFT JOIN users u ON u.id=a.staff_id ORDER BY a.timestamp DESC LIMIT 250`); res.json(r.rows); }
export async function notifications(req,res){ const r=await query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50',[req.user.id]); res.json(r.rows); }
export async function readNotification(req,res){ const r=await query('UPDATE notifications SET is_read=true WHERE id=$1 AND user_id=$2 RETURNING *',[req.params.id,req.user.id]); res.json(r.rows[0]||null); }
