import { query } from '../config/db.js';
import { audit, notify } from '../services/audit.js';
export async function list(req,res){
  let sql=`SELECT p.*,s.student_id,s.full_name,s.category FROM permissions p JOIN students s ON s.id=p.student_id`;
  const params=[]; if(req.user.role==='STUDENT'){ sql+=' WHERE s.user_id=$1'; params.push(req.user.id); } else if(req.query.status){ sql+=' WHERE p.status=$1'; params.push(req.query.status); } sql+=' ORDER BY p.created_at DESC'; const r=await query(sql,params); res.json(r.rows);
}
export async function create(req,res){ const s=await query('SELECT * FROM students WHERE user_id=$1',[req.user.id]); if(!s.rows[0]) return res.status(400).json({message:'Student profile not found'}); const {departure,returnTime,reason}=req.body||{}; const d=new Date(departure), rt=new Date(returnTime); if(!reason||Number.isNaN(d.getTime())||Number.isNaN(rt.getTime())||rt<=d) return res.status(400).json({message:'Provide valid departure, return and reason'}); const r=await query(`INSERT INTO permissions(student_id,requested_departure,requested_return,reason,status) VALUES($1,$2,$3,$4,'PENDING') RETURNING *`,[s.rows[0].id,d,rt,reason]); await audit(req.user.id,'STUDENT_SUBMITTED_PERMISSION','permission',r.rows[0].id,'Permission request submitted'); const admins=await query(`SELECT id FROM users WHERE role='ADMIN' AND status='ACTIVE'`); for(const a of admins.rows) await notify(a.id,'New permission request',`${s.rows[0].full_name} submitted a campus permission request.`,'INFO'); res.status(201).json(r.rows[0]); }
export async function approve(req,res){ const {durationHours,adminNote}=req.body||{}; const p=await query('SELECT p.*,s.student_id,s.full_name,s.user_id,s.category FROM permissions p JOIN students s ON s.id=p.student_id WHERE p.id=$1',[req.params.id]); if(!p.rows[0]) return res.status(404).json({message:'Permission not found'}); const x=p.rows[0]; const hours=Number(durationHours); if(!Number.isFinite(hours)||hours<=0||hours>168) return res.status(400).json({message:'Duration must be between 0 and 168 hours'}); const dep=new Date(x.requested_departure); const ret=new Date(dep.getTime()+hours*3600000); const r=await query(`UPDATE permissions SET approved_departure=$1,approved_return=$2,duration_hours=$3,status='APPROVED',admin_id=$4,admin_note=$5,updated_at=now() WHERE id=$6 RETURNING *`,[dep,ret,hours,req.user.id,adminNote||'',req.params.id]); await audit(req.user.id,'ADMIN_APPROVED_PERMISSION','permission',x.id,`Approved for ${hours} hours`); if(x.user_id) await notify(x.user_id,'Permission approved',`Your permission request was approved until ${ret.toLocaleString()}.`,'SUCCESS'); res.json(r.rows[0]); }
export async function deny(req,res){ const {adminNote}=req.body||{}; const p=await query('SELECT p.*,s.user_id FROM permissions p JOIN students s ON s.id=p.student_id WHERE p.id=$1',[req.params.id]); if(!p.rows[0]) return res.status(404).json({message:'Permission not found'}); const r=await query(`UPDATE permissions SET status='DENIED',admin_id=$1,admin_note=$2,updated_at=now() WHERE id=$3 RETURNING *`,[req.user.id,adminNote||'',req.params.id]); await audit(req.user.id,'ADMIN_DENIED_PERMISSION','permission',req.params.id,adminNote||'Permission denied'); if(p.rows[0].user_id) await notify(p.rows[0].user_id,'Permission denied',adminNote||'Your permission request was denied.','ALERT'); res.json(r.rows[0]); }
